// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afpuocoytmrnqsalsqzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmcHVvY295dG1ybnFzYWxzcXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTA4NDUsImV4cCI6MjA2ODYyNjg0NX0.cDD7inRbn8brlulFYBTT5FdTZ4LiKVciavbLpIQG-zQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});